'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>typeof v==='number'?v.toLocaleString('en-GB',{maximumFractionDigits:1}):String(v??'—');
const VIEWS=[
 {id:'clean',name:'Clean',groups:[],note:'Satellite imagery and the England boundary.'},
 {id:'admin',name:'Administrative areas',groups:['Administration'],defaults:['districts'],note:'Explore local authorities and their population estimates.'},
 {id:'population',name:'Population',groups:['Population'],defaults:['population'],note:'Switch between the density raster and 5 km hexagons.'},
 {id:'settlement',name:'Settlements & lights',groups:['Settlement'],defaults:['lights'],note:'Compare built-up surface, historical change and annual night lights.'},
 {id:'towns',name:'Towns & infrastructure',groups:['Towns','Transport','Infrastructure'],defaults:['towns','roads'],note:'Mapped settlements, transport links and infrastructure.'},
 {id:'services',name:'Services',groups:['Services'],defaults:['healthcare'],note:'Mapped facilities. Select a location to see its details.'},
 {id:'environment',name:'Environment & water',groups:['Environment','Water','Climate'],defaults:['landcover'],note:'Land cover, observed water, aquifers and climate evidence.'},
 {id:'access',name:'Travel time & access',groups:['Access'],defaults:['access_drive'],note:'Modelled access surfaces from 2015 and 2019; these are not live journey times.'}
];
let manifest,view='clean',epoch=0,active=new Map(),requests=new Map(),dataCache=new Map(),searchIndex=null,searchPromise=null,rasterId=null,loadCounter=0;
const map=L.map('map',{zoomControl:true,preferCanvas:true,minZoom:5,maxZoom:16});
const basemaps={imagery:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:18,attribution:'Imagery © Esri and contributors'}),light:L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors · © CARTO'})};
basemaps.imagery.addTo(map);L.control.scale({imperial:false}).addTo(map);
let label=L.marker([52.8,-1.6],{interactive:false,icon:L.divIcon({className:'country-label',html:'ENGLAND',iconSize:[120,20]})}).addTo(map);
let loadTimer;
function status(s){$('status').textContent=s||'';}
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(loadTimer);loadTimer=setTimeout(()=>$('toast').hidden=true,6500);}
async function getJSON(url){if(dataCache.has(url))return dataCache.get(url);const r=await fetch(url);if(!r.ok)throw Error('Could not load '+url+' ('+r.status+')');const j=await r.json();dataCache.set(url,j);return j;}
function showSidebar(open){$('sidebar').classList.toggle('hidden',!open);document.body.classList.toggle('sidebar-hidden',!open);document.body.classList.toggle('sidebar-open',open);$('viewsToggle').setAttribute('aria-expanded',String(open));}
$('viewsToggle').onclick=()=>showSidebar($('sidebar').classList.contains('hidden'));
$('closeViews').onclick=()=>showSidebar(false);
$('fit').onclick=()=>fit();
$('basemap').onchange=e=>{Object.values(basemaps).forEach(l=>map.removeLayer(l));basemaps[e.target.value].addTo(map);document.body.classList.toggle('light',e.target.value==='light');};
$('collapseLegend').onclick=()=>{$('legend').hidden=true;$('expandLegend').hidden=false;};
$('expandLegend').onclick=()=>{$('legend').hidden=false;$('expandLegend').hidden=true;};
$('coverageButton').onclick=()=>$('coverage').showModal();$('closeCoverage').onclick=()=>$('coverage').close();
$('coverage').onclick=e=>{if(e.target===$('coverage')){const b=$('coverage').getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)$('coverage').close();}};
function fit(){map.fitBounds(manifest.bounds,{paddingTopLeft:innerWidth>800&&!$('sidebar').classList.contains('hidden')?[350,25]:[25,25],paddingBottomRight:[35,35]});}
function densityColor(v){return v>=5000?'#7f0000':v>=2000?'#e34a33':v>=500?'#fc8d59':v>=100?'#fdbb84':v>=10?'#fee8c8':'#fff7ec';}
function styleFor(layer,f){const s=layer.style||{},p=f.properties||{};if(s.metric)return {color:'#6b766b',weight:.55,fillColor:p[s.metric]==null?'#ddd':densityColor(p[s.metric]),fillOpacity:.66};if(s.categorical){if(s.palette?.[p.category])return {color:'#697665',weight:.5,fillColor:s.palette[p.category],fillOpacity:.68};let h=0;for(const c of String(p.category||''))h=(h*31+c.charCodeAt(0))|0;const colors=['#e8c994','#a7c9c2','#cfb3ca','#acc28c','#bcc8e0','#dba597'];return {color:'#697665',weight:.5,fillColor:colors[Math.abs(h)%colors.length],fillOpacity:.68};}return {color:s.color||'#637d67',weight:layer.id==='roads'?2.3:1.1,fillOpacity:s.outline?0:.08,opacity:.85};}
function popup(layer,f){const p=f.properties||{};let html='<h3>'+esc(p.name||layer.title)+'</h3><table>';const names={code:'Area code',area_km2:'Land area · km²',population_2025:'Population · 2025',density_km2:'People / km²',population_coverage_pct:'Population coverage · %',category:'Type',operator:'Operator',ref:'Reference',opening_hours:'Opening hours',wheelchair:'Wheelchair access','addr:postcode':'Postcode',capacity:'Capacity'};for(const [k,label]of Object.entries(names)){if(p[k]!=null)html+='<tr><td>'+esc(label)+'</td><td>'+esc(fmt(p[k]))+'</td></tr>';}if(layer.id==='groundwater'){for(const[k,v]of Object.entries(p))if(!['name','category'].includes(k))html+='<tr><td>'+esc(k)+'</td><td>'+esc(v)+'</td></tr>';}html+='</table>';if(p.website&&/^https?:\/\//i.test(p.website))html+='<p><a target="_blank" rel="noopener noreferrer" href="'+esc(p.website)+'">Organisation website ↗</a></p>';if(p.osm_id&&/^\d+$/.test(String(p.osm_id))&&['node','way','relation'].includes(p.osm_type))html+='<a target="_blank" rel="noopener noreferrer" href="https://www.openstreetmap.org/'+p.osm_type+'/'+p.osm_id+'">OpenStreetMap record ↗</a>';return html+'<small>'+esc(layer.source)+' · '+esc(layer.date)+'</small>';}
function layerLabel(layer){let small=layer.kind==='raster'?(layer.coverage_pct<99.5?'Partial coverage · '+layer.coverage_pct+'%':''):fmt(layer.count)+' mapped features';if(layer.id==='built2030')small='Projection';return '<span>'+esc(layer.title)+(small?'<small>'+esc(small)+'</small>':'')+'</span>';}
function renderViews(){const box=$('views');box.innerHTML='';VIEWS.forEach((v,i)=>{const b=document.createElement('button');b.dataset.view=v.id;b.className=v.id===view?'active':'';b.setAttribute('aria-pressed',String(v.id===view));b.innerHTML='<small>0'+(i+1)+'</small>'+esc(v.name);b.onclick=()=>setView(v.id);box.append(b);});}
function renderLayers(){const v=VIEWS.find(x=>x.id===view);$('layerHeading').textContent=v.name;$('viewDescription').textContent=v.note;const list=manifest.layers.filter(l=>v.groups.includes(l.group));$('layers').innerHTML='';if(!list.length&&view!=='clean'){$('layers').innerHTML='<p class="empty">No usable source was found for this view. See Data & coverage for the remaining gaps.</p>';return;}list.forEach(l=>{const row=document.createElement('label');row.className='layer-option';const input=document.createElement('input');input.type='checkbox';input.dataset.layer=l.id;input.checked=active.has(l.id)||requests.has(l.id);input.onchange=()=>toggle(l.id,input.checked);row.append(input);const span=document.createElement('span');span.innerHTML=layerLabel(l);row.append(span);$('layers').append(row);});}
function remove(id){const pending=requests.get(id);if(pending?.mapLayer)map.removeLayer(pending.mapLayer);const entry=active.get(id);if(entry){map.removeLayer(entry.mapLayer);active.delete(id);}requests.delete(id);if(rasterId===id)rasterId=null;}
function setView(id){epoch++;for(const id of new Set([...active.keys(),...requests.keys()]))remove(id);requests.clear();rasterId=null;view=id;map.closePopup();$('legend').hidden=true;$('expandLegend').hidden=true;status('');renderViews();renderLayers();const v=VIEWS.find(x=>x.id===id);const available=manifest.layers.filter(l=>v.groups.includes(l.group));let defaults=(v.defaults||[]).filter(x=>available.some(l=>l.id===x));if(!defaults.length&&available.length)defaults=[available[0].id];defaults.forEach(x=>toggle(x,true));history.replaceState(null,'','#'+id);}
async function toggle(id,on){const layer=manifest.layers.find(x=>x.id===id);if(!layer)return;if(!on){remove(id);renderLayers();renderLegend();return;}if(active.has(id)||requests.has(id))return;
 if(layer.kind==='raster'||id==='hexes'){for(const [k,v]of [...active])if(v.layer.kind==='raster'||k==='hexes')remove(k);for(const k of [...requests.keys()]){const l=manifest.layers.find(x=>x.id===k);if(l.kind==='raster'||k==='hexes')remove(k);}}
 const token={epoch,id,serial:++loadCounter};requests.set(id,token);renderLayers();status('Loading '+layer.title+'…');
 try{let mapLayer;
 if(layer.kind==='raster'){mapLayer=L.imageOverlay(layer.files[0],layer.bounds,{opacity:.86,interactive:false});token.mapLayer=mapLayer;await new Promise((resolve,reject)=>{mapLayer.once('load',resolve);mapLayer.once('error',()=>reject(Error('The raster image could not be loaded. Toggle it to retry.')));mapLayer.addTo(map);});if(requests.get(id)!==token||token.epoch!==epoch){map.removeLayer(mapLayer);return;}rasterId=id;}
 else{mapLayer=L.geoJSON(null,{style:f=>styleFor(layer,f),pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:layer.id==='towns'?3:4,weight:1,color:'#fff',fillColor:layer.style?.color||'#496b61',fillOpacity:.9}),onEachFeature:(f,l)=>{l.bindPopup(()=>popup(layer,f),{maxWidth:330});if(layer.id==='towns'&&['city','town'].includes(f.properties?.category))l.bindTooltip(f.properties.name,{direction:'top',className:'town-label'});}});let count=0;for(const file of layer.files){if(requests.get(id)!==token||token.epoch!==epoch)return;const json=await getJSON(file);mapLayer.addData(json);count++;status('Loading '+layer.title+' · '+count+'/'+layer.files.length);if(count%3===0)await new Promise(r=>setTimeout(r,0));}if(requests.get(id)!==token||token.epoch!==epoch)return;mapLayer.addTo(map);}
 active.set(id,{mapLayer,layer});requests.delete(id);renderLayers();renderLegend();if(!requests.size)status('');
 }catch(e){if(token.mapLayer)map.removeLayer(token.mapLayer);if(requests.get(id)===token){requests.delete(id);status('');renderLayers();toast(e.message);}}}
function renderLegend(focusId){if(!active.size){$('legend').hidden=true;$('expandLegend').hidden=true;return;}const chosen=active.get(focusId)||[...active.values()].at(-1),l=chosen.layer;$('legendTitle').textContent=l.title;let html=active.size>1?'<label class=legend-unit>Map key for<select id=keyLayer>'+[...active.values()].map(x=>'<option value="'+esc(x.layer.id)+'"'+(x.layer.id===l.id?' selected':'')+'>'+esc(x.layer.title)+'</option>').join('')+'</select></label>':'';if(l.legend){html+='<p class="legend-unit">'+esc(l.unit)+'</p>';for(const item of l.legend)html+='<div class="legend-row"><span class="swatch" style="background:'+item.color+'"></span>'+esc(item.label)+'</div>';}else if(l.style?.metric){for(const[value,label]of [[0,'< 10'],[10,'10–100'],[100,'100–500'],[500,'500–2,000'],[2000,'2,000–5,000'],[5000,'≥ 5,000']])html+='<div class="legend-row"><span class="swatch" style="background:'+densityColor(value)+'"></span>'+label+'</div>';html+='<p class="legend-unit">People / km²</p>';}else{html+='<p>'+fmt(l.count)+' mapped features</p>';if(active.size>1)html+='<p class="muted">Also shown: '+[...active.values()].filter(x=>x.layer.id!==l.id).map(x=>esc(x.layer.title)).join(', ')+'</p>';}
 if(l.kind==='raster')html+='<p class="legend-unit">Overlay opacity</p><input class="opacity" id="opacity" type="range" min="10" max="100" value="86" aria-label="Overlay opacity">';
 html+='<div class="source"><strong>'+esc(l.date)+'</strong><br>'+esc(l.source)+'<p>'+esc(l.note)+'</p>'+(l.kind==='raster'?'<span class="coverage-tag">Valid display coverage: '+l.coverage_pct+'%</span>':'')+'</div>';$('legendBody').innerHTML=html;if($('keyLayer'))$('keyLayer').onchange=e=>renderLegend(e.target.value);if($('opacity'))$('opacity').oninput=e=>chosen.mapLayer.setOpacity(Number(e.target.value)/100);$('legend').hidden=false;$('expandLegend').hidden=true;}
map.on('click',async e=>{if(!rasterId)return;const id=rasterId,layer=manifest.layers.find(l=>l.id===id);try{const grid=await getJSON(layer.grid);if(rasterId!==id)return;const p=L.CRS.EPSG3857.project(e.latlng),b=grid.boundsMercator;const x=Math.floor((p.x-b[0])/(b[2]-b[0])*grid.nativeWidth/grid.step),y=Math.floor((b[3]-p.y)/(b[3]-b[1])*grid.nativeHeight/grid.step);if(x<0||x>=grid.width||y<0||y>=grid.height)return;const value=grid.values[y*grid.width+x];const display=value==null?'No valid data':layer.categories?layer.categories[String(Math.round(value))]||fmt(value):fmt(value)+' '+layer.unit;L.popup().setLatLng(e.latlng).setContent('<h3>'+esc(layer.title)+'</h3><strong>'+esc(display)+'</strong><small>Coarse inspection sample from the web display. '+esc(layer.date)+'. Use district or hexagon values for population totals.</small>').openOn(map);}catch(err){toast(err.message);}});
async function prepareSearch(){
 if(searchIndex)return;if(searchPromise)return searchPromise;
 searchPromise=(async()=>{const index=[];for(const layer of manifest.layers.filter(l=>['districts','towns'].includes(l.id))){for(const file of layer.files){const data=await getJSON(file);for(const f of data.features){let bounds=null,lat,lng;if(f.geometry.type==='Point'){[lng,lat]=f.geometry.coordinates;}else{bounds=L.geoJSON(f).getBounds();const c=bounds.getCenter();lat=c.lat;lng=c.lng;}index.push({name:String(f.properties.name||''),label:f.properties.name+(layer.id==='districts'?' · local authority':''),lat,lng,bounds});}}}searchIndex=index;})();
 try{await searchPromise;}finally{searchPromise=null;}
}
let searchTimer;$('search').addEventListener('focus',()=>prepareSearch().catch(e=>toast(e.message)));$('search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(async()=>{const q=$('search').value.trim().toLowerCase();$('searchResults').innerHTML='';if(q.length<2)return;try{await prepareSearch();for(const item of searchIndex.filter(x=>x.name.toLowerCase().includes(q)).slice(0,8)){const button=document.createElement('button');button.textContent=item.label;button.onclick=()=>{if(item.bounds)map.fitBounds(item.bounds,{padding:[30,30],maxZoom:11});else map.setView([item.lat,item.lng],12);$('searchResults').innerHTML='';if(innerWidth<800)showSidebar(false);};$('searchResults').append(button);}}catch(e){toast(e.message);}},220);};
function coverage(){let rows='';for(const l of manifest.layers)rows+='<tr><td>'+esc(l.title)+'</td><td>'+esc(l.date)+'</td><td>'+esc(l.kind==='raster'?l.coverage_pct+'% of display mask':fmt(l.count)+' records')+'</td><td>'+esc(l.source)+'</td></tr>';$('coverageRows').innerHTML=rows;$('issues').innerHTML=manifest.issues.map(x=>'<li><strong>'+esc(x.layer)+':</strong> '+esc(x.message)+'</li>').join('')||'<li>No processing gaps reported.</li>';$('coverageSummary').textContent=manifest.layers.length+' available layers · '+manifest.district_count+' local authorities'+(manifest.population_total?' · '+fmt(manifest.population_total)+' modelled residents (2025)':'');$('buildDate').textContent='Built '+new Date(manifest.built_at).toLocaleString('en-GB')+'. Map attribution is retained with each source.';}
(async()=>{try{manifest=await getJSON('manifest.json');const outline=await getJSON('data/outline.geojson');L.geoJSON(outline,{interactive:false,style:{color:'#142f24',weight:1.3,fill:false}}).addTo(map);fit();renderViews();coverage();if(innerWidth<800)showSidebar(false);const hash=location.hash.slice(1);setView(VIEWS.some(v=>v.id===hash)?hash:'clean');status('');}catch(e){status('Map could not open');toast(e.message+' Refresh to try again.');}})();
