'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(n,d=0)=>n==null?'—':typeof n==='number'?n.toLocaleString('en-GB',{maximumFractionDigits:d}):String(n);
const VIEWS=[['clean','Clean','Search for a place, then choose a map view or open an area briefing.'],['needs','Community needs','Compare financial pressures and barriers to accessing support.'],['flood','Flood exposure','Compare Environment Agency long-term flood exposure summaries.'],['partners','Local partners','Community foundation offices from the UKCF directory.'],['admin','Administrative areas','Select a local authority to see its population and area.'],['population','Population','Compare the population surface, hexagons and local authorities.'],['settlement','Settlements & lights','Explore annual night lights and change in built-up surface.'],['towns','Towns & infrastructure','Towns, transport links and strategic infrastructure.'],['services','Services','Explore mapped facilities by service type.'],['access','Travel time / access','Historical modelled travel times to healthcare and cities.'],['environment','Environment','Land cover, surface water, hydrogeology and climate.']];
const ENV=[['land','Land cover',['landcover']],['water','Surface water',['water_occurrence','water_seasonality','water_recurrence','water_change','water_transitions','water_extent']],['ground','Groundwater',['groundwater','water_infrastructure']],['climate','Rainfall & drought',['rainfall','rainfall_normals','drought','drought_latest']]];
const BLUE=['#eff6ff','#dbeafe','#93c5fd','#3b82f6','#1d4ed8','#08306b'],DENSITY=[10,100,500,2000,5000],COUNT=[1000,5000,10000,50000,150000];
let preparednessData,foundationFeatures=[],manifest,view='clean',environment='land',primaryId=null,epoch=0,loadSerial=0,selectedArea=null,selectionLayer=null,areas=[],searchIndex=null,searchPromise=null,pointFilter=new Set(),pending=new Map(),active=new Map(),cache=new Map(),alias={},analysisRows=[],rasterId=null,contextIds=new Set();
const map=L.map('map',{preferCanvas:true,minZoom:5,maxZoom:17,zoomSnap:.25,zoomControl:true,zoomAnimation:false});
const basemaps={imagery:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:18,attribution:'Imagery © Esri & contributors'}),light:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}',{maxNativeZoom:16,maxZoom:19,attribution:'Esri, HERE, Garmin, © OpenStreetMap contributors'})};basemaps.light.addTo(map);document.body.classList.add('light');L.control.scale({imperial:false}).addTo(map);
map.createPane('countryOutline');map.getPane('countryOutline').style.zIndex=420;map.getPane('countryOutline').style.pointerEvents='none';map.createPane('selectedArea');map.getPane('selectedArea').style.zIndex=460;map.getPane('selectedArea').style.pointerEvents='none';
L.marker([52.8,-1.7],{interactive:false,icon:L.divIcon({className:'country-label',html:'ENGLAND',iconSize:[120,20]})}).addTo(map);
function status(s){$('status').textContent=s||'';}let toastTimer;function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,7000);}
async function getJSON(url){if(cache.has(url))return cache.get(url);const p=fetch(url).then(r=>{if(!r.ok)throw Error('Could not load this layer. Please try again.');return r.json();});cache.set(url,p);try{const r=await p;if(cache.size>220)cache.delete(cache.keys().next().value);return r;}catch(e){cache.delete(url);throw e;}}
function layer(id){return alias[id]||manifest.layers.find(l=>l.id===id);}
function color(value,breaks=DENSITY){if(value==null)return '#d9dfd9';return BLUE[breaks.filter(b=>value>=b).length];}
function intersects(a,b){return a[0]<=b[2]&&a[2]>=b[0]&&a[1]<=b[3]&&a[3]>=b[1];}
function viewport(){const b=map.getBounds().pad(.15);return [b.getWest(),b.getSouth(),b.getEast(),b.getNorth()];}
function pointInRing(p,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
function pointInArea(p,f){const g=f.geometry;const polygons=g.type==='Polygon'?[g.coordinates]:g.type==='MultiPolygon'?g.coordinates:[];return polygons.some(r=>pointInRing(p,r[0])&&!r.slice(1).some(h=>pointInRing(p,h)));}
function selectionAllows(f){return !selectedArea||f.geometry.type!=='Point'||pointInArea(f.geometry.coordinates,selectedArea);}
function showPanel(open){document.body.classList.toggle('panel-hidden',!open);$('panel').classList.toggle('mobile-open',open);$('panelToggle').setAttribute('aria-expanded',String(open));}
function fit(){map.stop();map.fitBounds(manifest.bounds,{animate:false,paddingTopLeft:[25,30],paddingBottomRight:innerWidth>1024&&!document.body.classList.contains('panel-hidden')?[370,35]:[25,70]});}
document.querySelector('.brand').onclick=e=>{e.preventDefault();setView('clean',{keepArea:false});};
$('panelToggle').onclick=()=>showPanel(true);$('closePanel').onclick=()=>showPanel(false);$('fit').onclick=fit;$('basemap').onchange=e=>{Object.values(basemaps).forEach(l=>map.removeLayer(l));basemaps[e.target.value].addTo(map);document.body.classList.toggle('light',e.target.value==='light');for(const item of active.values())if(item.features)drawVector(item);};
$('opacityButton').onclick=()=>{$('opacityControls').hidden=!$('opacityControls').hidden;$('opacityButton').setAttribute('aria-expanded',String(!$('opacityControls').hidden));};$('opacity').oninput=e=>{const entry=active.get(primaryId);if(entry?.layer.kind==='raster')entry.mapLayer.setOpacity(Number(e.target.value)/100);};
function renderViews(){
 const box=$('views');box.replaceChildren();const main=['clean','needs','flood','partners','population','services'];
 const add=(parent,id)=>{const name=VIEWS.find(v=>v[0]===id)[1],b=document.createElement('button');b.dataset.view=id;b.textContent=name;b.className=id===view?'active':'';b.setAttribute('aria-pressed',String(id===view));b.onclick=()=>setView(id);parent.append(b);};
 for(const id of main)add(box,id);const more=document.createElement('details');more.className='more-views';more.open=!main.includes(view);more.innerHTML='<summary>More map views <span>5</span></summary>';const grid=document.createElement('div');grid.className='extra-views';for(const[id]of VIEWS)if(!main.includes(id))add(grid,id);more.append(grid);box.append(more);
}
function choiceBox(parent,choices,selected,callback){const div=document.createElement('div');div.className='choice-buttons';for(const c of choices){const [id,title,enabled=true]=c,b=document.createElement('button');b.textContent=title;b.dataset.layer=id;b.className=id===selected?'active':'';b.setAttribute('aria-pressed',String(id===selected));b.disabled=!enabled;if(!enabled)b.title='Unavailable in this release';b.onclick=()=>callback(id);div.append(b);}parent.append(div);return div;}
function has(id){return !!layer(id);}
function availableChoices(ids){return ids.map(([id,name])=>[id,name,has(id)]);}
function defaultLayer(){const candidates={flood:['district_flood_rofrs_people_high_medium_pct'],needs:['district_need_imd_top10_pct'],partners:['community_foundations'],clean:[],admin:['district_boundaries'],population:['population','hex_density','district_density'],settlement:['lights','built2020','built2000','built2030'],towns:['towns','roads'],services:['healthcare','education','public_services'],access:['access_drive','access_walk','access_cities'],environment:ENV.find(e=>e[0]===environment)[2]};return candidates[view].find(has)||null;}
function removeLayer(id){const p=pending.get(id);if(p?.mapLayer)map.removeLayer(p.mapLayer);pending.delete(id);const e=active.get(id);if(e)map.removeLayer(e.mapLayer);active.delete(id);if(rasterId===id)rasterId=null;}
function clearLayers(){epoch++;for(const id of new Set([...active.keys(),...pending.keys()]))removeLayer(id);contextIds.clear();primaryId=null;rasterId=null;pointFilter.clear();map.closePopup();status('');}
function setView(id,{keepArea=true}={}){if(!VIEWS.some(v=>v[0]===id))id='clean';clearLayers();view=id;if(!keepArea)clearArea();primaryId=defaultLayer();showMap();renderViews();renderControls();renderLegend();if(primaryId)loadLayer(primaryId);if(view==='towns'&&primaryId!=='roads'&&has('roads')){contextIds.add('roads');loadLayer('roads',true);}history.replaceState(null,'','#'+view);}
function choose(id){if(primaryId)removeLayer(primaryId);primaryId=id;pointFilter.clear();renderControls();renderLegend();loadLayer(id);}
function renderControls(){const meta=VIEWS.find(v=>v[0]===view);$('activeViewTitle').textContent=meta[1];$('viewHint').textContent=meta[2];$('viewHint').hidden=['needs','partners','flood'].includes(view);const box=$('themeControls'),metrics=$('metricControls');box.replaceChildren();metrics.replaceChildren();
 renderPreparednessControls(box,metrics);renderFloodControls(box,metrics);
 if(view==='population'){choiceBox(box,availableChoices([['population','Population surface'],['hex_density','5 km hexagons'],['district_density','Local authorities']]),primaryId?.startsWith('hex')?'hex_density':primaryId?.startsWith('district')?'district_density':primaryId,choose);if(primaryId&&primaryId!=='population'){const prefix=primaryId.startsWith('hex')?'hex':'district';choiceBox(metrics,[[prefix+'_density','People / km²'],[prefix+'_population','Population total']],primaryId,choose);}}
 if(view==='admin')choiceBox(box,availableChoices([['district_boundaries','Local authorities'],['counties','Counties / unitary areas']]),primaryId,choose);
 if(view==='settlement'){choiceBox(box,availableChoices([['lights','Night-time lights'],['built2020','Built-up · 2020'],['built2000','Built-up · 2000'],['built_change','Change · 2000–2020']]),primaryId,choose);if(has('built2030')){const label=document.createElement('label');label.className='layer-option';label.innerHTML='<input type="checkbox" '+(primaryId==='built2030'?'checked':'')+'> Show 2030 projection';label.querySelector('input').onchange=e=>choose(e.target.checked?'built2030':has('lights')?'lights':'built2020');box.append(label);}}
 if(view==='towns'){choiceBox(box,availableChoices([['towns','Towns & transport'],['ports_airports','Ports and airports'],['power','Energy infrastructure'],['water_infrastructure','Water infrastructure']]),primaryId,choose);const div=document.createElement('div');for(const[id,title]of [['roads','Major roads'],['minor_roads','Secondary / tertiary roads'],['railways','Railways'],['stations','Stations'],['power_lines','Power lines']])if(has(id))addCheckbox(div,id,title);box.append(div);}
 if(view==='services'){choiceBox(box,availableChoices([['healthcare','Healthcare'],['education','Education'],['public_services','Public services']]),primaryId,choose);renderPointFilters(metrics);}
 if(view==='access')choiceBox(box,availableChoices([['access_drive','Healthcare · motorised'],['access_walk','Healthcare · walking'],['access_cities','Time to cities']]),primaryId,choose);
 if(view==='environment'){choiceBox(box,ENV.map(e=>[e[0],e[1]]),environment,id=>{environment=id;if(primaryId)removeLayer(primaryId);primaryId=defaultLayer();pointFilter.clear();renderControls();renderLegend();if(primaryId)loadLayer(primaryId);});const ids=ENV.find(e=>e[0]===environment)[2].filter(has);if(ids.length){const select=document.createElement('select');select.className='control-select';select.setAttribute('aria-label','Environmental indicator');select.id='environmentIndicator';select.innerHTML=ids.map(id=>'<option value="'+id+'"'+(id===primaryId?' selected':'')+'>'+esc(layer(id).title)+'</option>').join('');select.onchange=e=>choose(e.target.value);metrics.append(select);}}
 if(view!=='clean'&&!primaryId){const p=document.createElement('p');p.className='availability';p.textContent='This theme is unavailable in the current release. Available sources and gaps are listed under Data sources & limitations.';metrics.append(p);}else if(view==='population'&&!has('population')){const p=document.createElement('p');p.className='availability';p.textContent='Local authority estimates are available. The population surface and hexagons are unavailable in this release.';metrics.append(p);}
 $('contextMenu').hidden=false;$('contextOptions').replaceChildren();for(const[id,title]of [['community_foundations','Community foundations'],['towns','Towns'],['roads','Major roads'],['district_boundaries','Local authorities'],['healthcare','Healthcare'],['stations','Stations'],['ports_airports','Ports / airports']])if(has(id)&&id!==primaryId)addCheckbox($('contextOptions'),id,title);
 renderDataContext(metrics);renderSelectionInfo();}
function addCheckbox(parent,id,title){const label=document.createElement('label');label.className='layer-option';const input=document.createElement('input');input.type='checkbox';input.checked=contextIds.has(id);input.dataset.context=id;input.onchange=e=>{if(e.target.checked){contextIds.add(id);loadLayer(id,true);}else{contextIds.delete(id);removeLayer(id);}renderControls();renderLegend();};label.append(input,document.createTextNode(title));parent.append(label);}
const HEALTH_NAMES={hospital:'Hospitals',clinic:'Clinics',doctors:'Doctors',doctor:'Doctors',pharmacy:'Pharmacies',dentist:'Dentists',centre:'Health centres',other:'Other mapped healthcare'};
function categoryFor(l,f){const c=f.properties.category;if(l.id!=='healthcare')return c;const normal={doctor:'doctors',health_centre:'centre',health_center:'centre',medical_centre:'centre'}[c]||c;return HEALTH_NAMES[normal]?normal:'other';}
function renderPointFilters(parent){const entry=active.get(primaryId);if(!entry?.features)return;const cats=[...new Set(entry.features.map(f=>categoryFor(entry.layer,f)))].filter(Boolean).sort();if(cats.length<2)return;const div=document.createElement('div');div.className='filter-pills';for(const cat of cats){const b=document.createElement('button');b.textContent=HEALTH_NAMES[cat]||cat.replaceAll('_',' ');b.className=pointFilter.size&&!pointFilter.has(cat)?'inactive':'active';b.setAttribute('aria-pressed',String(!pointFilter.size||pointFilter.has(cat)));b.onclick=()=>{if(!pointFilter.size)pointFilter=new Set(cats);if(pointFilter.has(cat))pointFilter.delete(cat);else pointFilter.add(cat);if(!pointFilter.size)pointFilter.add('__none__');drawVector(entry);renderControls();renderLegend();};div.append(b);}parent.append(div);const count=document.createElement('p');count.className='count-line';count.id='facilityCount';count.textContent=fmt(entry.visibleCount)+' facilities in the map area';parent.append(count);}
function styleFor(l,f){const s=l.style||{},p=f.properties||{};if(s.metric){const breaks=s.breaks||(s.metric==='population_2025'?COUNT:DENSITY);return {color:'#e8f0ec',weight:l.id.startsWith('district')?.6:.35,fillColor:p[s.metric]==null?'#d7dcdf':(s.colors||BLUE)[breaks.filter(b=>p[s.metric]>=b).length],fillOpacity:.82};}if(l.id==='groundwater')return {color:'#666c61',weight:.45,fillColor:s.palette?.[p.category]||'#c9d8b1',fillOpacity:.76};if(l.id==='district_boundaries'||l.id==='counties')return {color:document.body.classList.contains('light')?'#647d78':'#f4f5da',weight:l.id==='counties'?1.7:1,fillColor:'#193f35',fillOpacity:.025};const cat=p.category||'';return {color:l.id==='roads'?cat.startsWith('motorway')?'#e39a43':'#f1c673':s.color||'#536d61',weight:l.id==='roads'?2.1:l.id==='minor_roads'?1.2:1.3,opacity:.88,fillOpacity:.04};}
function popup(l,f){const p=f.properties||{};let html='<h3>'+esc(p.name||l.title)+'</h3><table>';const fields={category:'Type',region:'Directory region',address:'Office address',phone:'Telephone',code:'Area code',population_2025:'Population · 2025',density_km2:'People / km²',area_km2:'Area · km²',operator:'Operator',opening_hours:'Opening hours',wheelchair:'Wheelchair access','addr:postcode':'Postcode',capacity:'Capacity'};for(const[k,title]of Object.entries(fields))if(p[k]!=null)html+='<tr><td>'+esc(title)+'</td><td>'+esc(fmt(p[k],1))+'</td></tr>';if(l.id==='groundwater')for(const k of ['ROCK_UNIT','CHARACTER','FLOW_MECHA','SUMMARY'])if(p[k])html+='<tr><td>'+esc(k.replaceAll('_',' ').toLowerCase())+'</td><td>'+esc(p[k])+'</td></tr>';html+='</table>';if(p.website&&/^https?:\/\//i.test(p.website))html+='<p><a href="'+esc(p.website)+'" target="_blank" rel="noopener noreferrer">Organisation website ↗</a></p>';if(/^\d+$/.test(String(p.osm_id))&&['node','way','relation'].includes(p.osm_type))html+='<p><a href="https://www.openstreetmap.org/'+p.osm_type+'/'+p.osm_id+'" target="_blank" rel="noopener noreferrer">OpenStreetMap record ↗</a></p>';if(l.id==='community_foundations')html+='<p class="area-note">Office location. Check service area and current funding with the foundation.</p>';return html+'<small>'+esc(l.source)+' · '+esc(l.date)+'</small>';}
async function filesFor(l){if(l.overview&&map.getZoom()<l.overview.min_zoom)return [l.overview.file];if(!l.spatial)return l.files;const s=l.spatial;if(map.getZoom()<s.min_zoom)return s.overview?[s.overview]:[];const b=viewport();return s.chunks.filter(c=>intersects(c.bounds,b)).map(c=>c.file);}
async function loadLayer(id,context=false){const l=layer(id);if(!l)return;removeLayer(id);const token={epoch,serial:++loadSerial};pending.set(id,token);status('Loading '+l.title+'…');try{let e={layer:l,mapLayer:null,features:null,context,filesKey:''};if(l.kind==='raster'){const overlay=L.imageOverlay(l.files[0],l.bounds,{opacity:Number($('opacity').value)/100,interactive:false});token.mapLayer=overlay;await new Promise((resolve,reject)=>{overlay.once('load',resolve);overlay.once('error',()=>reject(Error('The map image could not load. Select the layer again to retry.')));overlay.addTo(map);});if(pending.get(id)!==token||token.epoch!==epoch){map.removeLayer(overlay);return;}e.mapLayer=overlay;rasterId=id;}else{const files=await filesFor(l);e.filesKey=files.join('|');const data=[];let i=0;for(const file of files){if(pending.get(id)!==token||token.epoch!==epoch)return;const fc=await getJSON(file);data.push(...fc.features.map(f=>mergePreparedness(f,l)));if(++i%4===0){status('Loading '+l.title+' · '+i+'/'+files.length);await new Promise(r=>setTimeout(r,0));}}if(pending.get(id)!==token||token.epoch!==epoch)return;e.features=data;e.mapLayer=L.featureGroup().addTo(map);drawVector(e);}active.set(id,e);pending.delete(id);if(l.kind!=='raster'&&(l.spatial||l.overview)&&(await filesFor(l)).join('|')!==e.filesKey){loadLayer(id,context);return;}renderLegend();if(id===primaryId&&view==='services')renderControls();if(!pending.size)status('');}catch(err){if(token.mapLayer)map.removeLayer(token.mapLayer);if(pending.get(id)===token){pending.delete(id);status('');toast(err.message);}}}
function drawVector(entry){entry.mapLayer.clearLayers();const l=entry.layer,fs=entry.features||[],isPoint=l.style?.points||fs[0]?.geometry.type==='Point';if(isPoint){const b=map.getBounds().pad(.08);let filtered=fs.filter(f=>f.geometry.type==='Point'&&b.contains([f.geometry.coordinates[1],f.geometry.coordinates[0]])&&(l.id==='community_foundations'||selectionAllows(f))&&(!(l.id===primaryId&&pointFilter.size)||pointFilter.has(categoryFor(l,f))));entry.visibleCount=filtered.length;const buckets=new Map(),z=map.getZoom();for(const f of filtered){const p=map.project([f.geometry.coordinates[1],f.geometry.coordinates[0]],z);const cell=z>=14?18:54,key=Math.floor(p.x/cell)+'/'+Math.floor(p.y/cell);if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(f);}for(const group of buckets.values()){if(group.length===1){const f=group[0],c=f.geometry.coordinates,p=f.properties,clr=l.style?.color||'#256654';const marker=L.circleMarker([c[1],c[0]],{radius:l.id==='towns'?(p.category==='city'?6:4):4.5,color:'#fff',weight:1.4,fillColor:clr,fillOpacity:.95});marker.bindPopup(()=>popup(l,f),{maxWidth:320});if(p.name)marker.bindTooltip(esc(p.name),{direction:'top',className:'town-tip'});entry.mapLayer.addLayer(marker);}else{let lat=0,lng=0;for(const f of group){lng+=f.geometry.coordinates[0];lat+=f.geometry.coordinates[1];}const marker=L.circleMarker([lat/group.length,lng/group.length],{radius:Math.min(27,12+Math.log(group.length)*2.4),color:'#fff',weight:2,fillColor:l.style?.color||'#256654',fillOpacity:.94});marker.bindTooltip(group.length>=1000?fmt(group.length/1000,1)+'k':String(group.length),{permanent:true,direction:'center',className:'cluster-label'});marker.on('click',()=>{if(z<16)map.setView(marker.getLatLng(),Math.min(17,z+2));else marker.bindPopup('<h3>'+fmt(group.length)+' mapped locations</h3>'+group.slice(0,15).map(f=>'<p>'+esc(f.properties.name||f.properties.category)+'</p>').join('')).openPopup();});entry.mapLayer.addLayer(marker);}}}else{const geo=L.geoJSON({type:'FeatureCollection',features:fs},{style:f=>styleFor(l,f),onEachFeature:(f,obj)=>{if(l.id.startsWith('district')){obj.on('click',()=>selectArea(f));const m=l.style?.metric;obj.bindTooltip(esc(f.properties.name)+(m?'<br>'+esc(f.properties[m]==null?'No matching data':metricValue(f.properties[m],m,1)+' · '+(l.unit||'')):''),{className:'town-tip'});}else obj.bindPopup(()=>popup(l,f),{maxWidth:330});}});entry.mapLayer.addLayer(geo);entry.visibleCount=fs.length;}}
let moveTimer;map.on('moveend',()=>{clearTimeout(moveTimer);moveTimer=setTimeout(async()=>{for(const[id,e]of [...active]){if(e.layer.kind==='raster')continue;if(e.layer.spatial||e.layer.overview){const files=await filesFor(e.layer);if(files.join('|')!==e.filesKey){loadLayer(id,e.context);continue;}}if(e.features[0]?.geometry.type==='Point')drawVector(e);}if(view==='services')renderControls();renderLegend();},160);});
function renderLegend(){if(layer(primaryId)?.kind!=='raster'){$('opacityControls').hidden=true;$('opacityButton').setAttribute('aria-expanded','false');}const entry=active.get(primaryId),l=layer(primaryId);$('opacityButton').hidden=!(l?.kind==='raster');if(!l){$('legend').innerHTML='<div class="legend-row"><span class="swatch line" style="border-color:#17251d"></span>England boundary</div><p class="legend-unit">December 2025 administrative geography</p>';return;}let html='<div class="legend-title">'+esc(l.title)+'</div>';if(l.style?.metric){const metric=l.style.metric,breaks=l.style.breaks||(metric==='population_2025'?COUNT:DENSITY),palette=l.style.colors||BLUE;html+='<p class="legend-unit">'+(l.unit|| (metric==='population_2025'?'Modelled residents · 2025':'People / km² · 2025'))+'</p><div class="legend-grid">';for(let i=0;i<palette.length;i++)html+='<div class="legend-row"><span class="swatch" style="background:'+palette[i]+'"></span>'+(i===0?'&lt; '+fmt(breaks[0]):i===breaks.length?'≥ '+fmt(breaks.at(-1)):fmt(breaks[i-1])+'–&lt; '+fmt(breaks[i]))+'</div>';html+='</div><div class="legend-row nodata-key"><span class="swatch" style="background:#d7dcdf"></span>No matching data</div>';}else if(l.legend){html+='<p class="legend-unit">'+esc(l.unit||'')+'</p><div class="legend-grid">'+l.legend.map(x=>'<div class="legend-row"><span class="swatch" style="background:'+esc(x.color)+'"></span>'+esc(x.label)+'</div>').join('')+'</div>';}else{html+='<div class="legend-row"><span class="swatch '+(l.style?.points?'point':'line')+'" style="background:'+esc(l.style?.color||'#6b8572')+';border-color:'+esc(l.style?.color||'#6b8572')+'"></span>'+esc(l.title)+'</div>';if(l.count)html+='<p class="legend-unit">'+fmt(l.count)+' mapped records'+(entry?.visibleCount!=null?' · '+fmt(entry.visibleCount)+' in this display':'')+'</p>';}
 if((l.spatial||l.overview)&&map.getZoom()<(l.spatial||l.overview).min_zoom)html+='<p class="legend-unit">'+(l.id==='roads'?'Motorways at this scale. Zoom in for other major roads.':l.id==='towns'?'Cities and towns at this scale. Zoom in for villages.':l.id==='power'?'Power stations at this scale. Zoom in for smaller infrastructure.':'Zoom in to see this detailed layer.')+'</p>';
 if(contextIds.size)html+='<p class="legend-unit">Context: '+[...contextIds].map(id=>esc(layer(id)?.title||id)).join(', ')+'</p>';
 html+='<div class="source-note"><strong>'+esc(l.date)+'</strong> · '+esc(l.source);if(l.source_url)html+=' · <a href="'+esc(l.source_url)+'" target="_blank" rel="noopener">Source ↗</a>';if(l.kind==='raster')html+='<p>Valid display coverage '+fmt(l.coverage_pct,1)+'%.</p>';html+='<details><summary>About this measure</summary><p>'+esc(l.note)+'</p></details></div>';$('legend').innerHTML=html;}
map.on('click',async e=>{if(!rasterId)return;const id=rasterId,l=layer(id);try{const grid=await getJSON(l.grid);if(id!==rasterId)return;const p=L.CRS.EPSG3857.project(e.latlng),b=grid.boundsMercator,x=Math.floor((p.x-b[0])/(b[2]-b[0])*grid.nativeWidth/grid.step),y=Math.floor((b[3]-p.y)/(b[3]-b[1])*grid.nativeHeight/grid.step);if(x<0||x>=grid.width||y<0||y>=grid.height)return;const value=grid.values[y*grid.width+x],v=value==null?'No valid data':l.categories?l.categories[String(Math.round(value))]||fmt(value):fmt(value,2)+' '+l.unit;L.popup().setLatLng(e.latlng).setContent('<h3>'+esc(l.title)+'</h3><strong>'+esc(v)+'</strong><small>Coarse web display sample · '+esc(l.date)+'. Original source resolution may be finer.</small>').openOn(map);}catch(err){toast(err.message);}});
async function loadAreas(){if(areas.length)return areas;const l=layer('districts');if(!l)return [];const fcs=await Promise.all(l.files.map(getJSON));areas=fcs.flatMap(d=>d.features).map(f=>mergePreparedness(f,layer('districts')));return areas;}
function selectArea(f,{zoom=false}={}){selectedArea=areas.find(a=>a.properties.code===f.properties.code)||f;if(selectionLayer)map.removeLayer(selectionLayer);selectionLayer=L.geoJSON(selectedArea,{pane:'selectedArea',interactive:false,style:{color:'#253f52',weight:3,fillOpacity:0,dashArray:'6 3'}}).addTo(map);if(zoom){map.stop();map.fitBounds(selectionLayer.getBounds(),{animate:false,paddingTopLeft:[30,70],paddingBottomRight:innerWidth>1024?[370,40]:[25,260],maxZoom:11});}renderAreaCard();addAreaBriefing();renderSelectionInfo();for(const e of active.values())if(e.features?.[0]?.geometry.type==='Point')drawVector(e);if(view==='services')renderControls();if(innerWidth<=1024)showPanel(false);}
function renderSelectionInfo(){$('selectionInfo').hidden=!selectedArea;if(selectedArea){$('selectionInfo').className='count-line';$('selectionInfo').textContent='Selected area: '+selectedArea.properties.name;}}
function renderAreaCard(){const p=selectedArea.properties;$('clearSelection').hidden=false;$('areaCard').hidden=false;$('areaCard').innerHTML='<button class="close" id="closeArea" aria-label="Close area details">×</button><p class="eyebrow">LOCAL AUTHORITY · '+esc(p.code)+'</p><h2>'+esc(p.name)+'</h2><div class="area-stats"><div><strong>'+fmt(p.population_2025)+'</strong><span>Modelled population · 2025</span></div><div><strong>'+fmt(p.density_km2,1)+'</strong><span>People / km²</span></div><div><strong>'+fmt(p.area_km2,1)+'</strong><span>Area · km²</span></div><div><strong>'+fmt(p.population_coverage_pct,1)+'%</strong><span>Raster footprint</span></div></div><div class="area-actions"><button id="areaServices">Show healthcare</button><button id="areaExport">Export area · CSV</button></div><p class="area-note">WorldPop 2025 model estimate. Valid source cells describes the raster footprint, not a census response rate.</p>';$('closeArea').onclick=clearArea;$('areaServices').onclick=()=>{setView('services');if(innerWidth<=1024)showPanel(false);};$('areaExport').onclick=()=>exportRows([p],'England-'+p.code+'.csv');}
function clearArea(){selectedArea=null;if(selectionLayer)map.removeLayer(selectionLayer);selectionLayer=null;$('areaCard').hidden=true;$('clearSelection').hidden=true;renderSelectionInfo();for(const e of active.values())if(e.features?.[0]?.geometry.type==='Point')drawVector(e);if(view==='services')renderControls();}$('clearSelection').onclick=clearArea;
async function prepareSearch(){if(searchIndex)return;if(searchPromise)return searchPromise;searchPromise=(async()=>{const all=await loadAreas();const index=all.map(f=>({name:f.properties.name,type:'Local authority',feature:f}));const towns=layer('towns');if(towns){const data=await Promise.all(towns.files.map(getJSON));for(const d of data)for(const f of d.features)index.push({name:String(f.properties.name||''),type:f.properties.category,feature:f});}searchIndex=index;})();try{await searchPromise;}finally{searchPromise=null;}}
let searchTimer,searchOption=-1;
function closeSearch(){searchOption=-1;$('searchResults').replaceChildren();$('search').setAttribute('aria-expanded','false');$('search').removeAttribute('aria-activedescendant');}
$('search').addEventListener('focus',()=>prepareSearch().catch(e=>toast(e.message)));
$('search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(async()=>{
 const q=$('search').value.trim().toLowerCase();closeSearch();if(q.length<2)return;
 try{await prepareSearch();if($('search').value.trim().toLowerCase()!==q)return;
 const found=searchIndex.filter(x=>x.name.toLowerCase().includes(q)||String(x.feature.properties.code||'').toLowerCase()===q).sort((a,b)=>(b.name.toLowerCase()===q)-(a.name.toLowerCase()===q)||a.name.localeCompare(b.name)).slice(0,9);
 $('search').setAttribute('aria-expanded','true');
 if(!found.length){const p=document.createElement('p');p.className='search-empty';p.textContent='No matches. Try a town or local authority name.';$('searchResults').append(p);}
 for(const item of found){const b=document.createElement('button');b.id='searchOption'+$('searchResults').children.length;b.tabIndex=-1;b.setAttribute('role','option');b.setAttribute('aria-selected','false');b.innerHTML=esc(item.name)+'<small>'+esc(item.type)+'</small>';
 b.onclick=()=>{closeSearch();$('search').value=item.name;if(item.type==='Local authority')selectArea(item.feature,{zoom:true});else{const c=item.feature.geometry.coordinates;clearArea();const authority=areas.find(f=>pointInArea(c,f));if(authority)selectArea(authority);map.setView([c[1],c[0]],12);L.popup().setLatLng([c[1],c[0]]).setContent(popup(layer('towns'),item.feature)).openOn(map);}if(innerWidth<=1024)showPanel(false);};$('searchResults').append(b);}
 }catch(err){toast(err.message);}},180);};
$('search').onkeydown=e=>{const options=[...$('searchResults').querySelectorAll('[role="option"]')];if(e.key==='Escape'){closeSearch();return;}if(!options.length)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();searchOption=(searchOption+(e.key==='ArrowDown'?1:-1)+options.length)%options.length;options.forEach((b,i)=>b.setAttribute('aria-selected',String(i===searchOption)));$('search').setAttribute('aria-activedescendant',options[searchOption].id);options[searchOption].scrollIntoView({block:'nearest'});}else if(e.key==='Enter'){e.preventDefault();options[Math.max(0,searchOption)].click();}};
document.addEventListener('click',e=>{if(!e.target.closest('.searchbox'))closeSearch();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeSearch();if($('sources').open)$('sources').close();}});
function showMap(){$('partnersPage').hidden=true;$('partnersTab').classList.remove('active');$('analysisPage').hidden=true;$('mapPage').hidden=false;$('mapTab').classList.add('active');$('analysisTab').classList.remove('active');setTimeout(()=>map.invalidateSize(),0);}
async function showAnalysis(){$('partnersPage').hidden=true;$('partnersTab').classList.remove('active');history.replaceState(null,'','#analysis');$('mapPage').hidden=true;$('analysisPage').hidden=false;$('analysisTab').classList.add('active');$('mapTab').classList.remove('active');try{await loadAreas();const totalArea=areas.reduce((s,a)=>s+(a.properties.area_km2||0),0);$('nationalStats').innerHTML=[['Modelled population',fmt(manifest.population_total),'WorldPop · 2025'],['Population density',fmt(manifest.population_total/totalArea,1),'People / km²'],['Local authorities',fmt(areas.length),'December 2025'],['England land area',fmt(totalArea),'km² · boundary-derived']].map(([label,value,note])=>'<div class="kpi"><span>'+label+'</span><strong>'+value+'</strong><span>'+note+'</span></div>').join('');renderAnalysis();}catch(e){toast(e.message);}}
const METRICS={population_2025:{title:'Population · 2025',unit:'residents',decimals:0},density_km2:{title:'Population density',unit:'people / km²',decimals:1},area_km2:{title:'Land area',unit:'km²',decimals:1}};
function renderAnalysis(){
 const metric=$('analysisMetric').value,meta=METRICS[metric],q=$('areaSearch').value.toLowerCase(),sort=$('analysisSort').value;
 analysisRows=areas.map(a=>a.properties).filter(p=>p.name.toLowerCase().includes(q)||p.code.toLowerCase().includes(q));
 analysisRows.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):a[metric]==null?(b[metric]==null?a.name.localeCompare(b.name):1):b[metric]==null?-1:(sort==='desc'?-1:1)*(a[metric]-b[metric])||a.name.localeCompare(b.name));
 const max=Math.max(1,...areas.map(a=>a.properties[metric]||0)),valid=analysisRows.filter(p=>p[metric]!=null).length;
 $('analysisSummary').textContent='Areas shown: '+fmt(analysisRows.length)+' · '+valid+' with data · '+meta.unit+(meta.period?' · '+meta.period:'')+'.'+(meta.note?' '+meta.note:'');
 const box=$('rankings');box.replaceChildren();
 const head=document.createElement('div');head.className='ranking-head';head.innerHTML='<span>Keep</span><span>Local authority</span><span>'+esc(meta.title)+'</span><span>Value</span><span></span>';box.append(head);
 if(!analysisRows.length){const p=document.createElement('p');p.className='no-data';p.textContent='No areas match. Try a shorter name or an authority code.';box.append(p);}
 for(const p of analysisRows){const row=document.createElement('div');row.className='ranking-row';row.dataset.code=p.code;
 const check=document.createElement('input');check.type='checkbox';check.checked=shortlist.has(p.code);check.setAttribute('aria-label','Shortlist '+p.name);check.onchange=()=>{toggleShortlist(p.code);check.checked=shortlist.has(p.code);};
 const name=document.createElement('button');name.className='area-link';name.textContent=p.name;
 const locate=()=>{setView(FLOOD_METRICS[metric]?'flood':NEEDS_METRICS[metric]?'needs':'population');if(FLOOD_METRICS[metric])choose('district_flood_'+metric);else if(NEEDS_METRICS[metric])choose('district_need_'+metric);else if(['density_km2','population_2025'].includes(metric))choose(metric==='population_2025'?'district_population':'district_density');selectArea(areas.find(a=>a.properties.code===p.code),{zoom:true});};name.onclick=locate;
 const bar=document.createElement('span');bar.className='bar-track';bar.setAttribute('aria-hidden','true');if(p[metric]!=null){const fill=document.createElement('span');fill.style.width=100*p[metric]/max+'%';bar.append(fill);}else bar.classList.add('missing-value');
 const value=document.createElement('span');value.className='rank-value';value.textContent=p[metric]==null?'No data':metricValue(p[metric],metric,meta.decimals);
 const link=document.createElement('button');link.className='rank-map';link.textContent='Map ↗';link.setAttribute('aria-label','Show '+p.name+' on map');link.onclick=locate;row.append(check,name,bar,value,link);box.append(row);}
 renderShortlist();
}
function exportRows(rows,name){
 const cols=[...new Set(['code','name','population_2025','density_km2','area_km2','population_coverage_pct',...Object.keys(manifest.analysis_metrics||{}),'census_residents','census_households',...Object.values(censusData.metrics).map(m=>m.numerator_field),...Object.keys(Object.values(floodData.records)[0]).filter(k=>k.startsWith('rofrs_')||k.startsWith('rofsw_'))])];
 const out=rows.map(p=>{const row=Object.fromEntries(cols.map(k=>[k,p[k]??'']));return {...row,...floodExportMetadata(p),population_source:'WorldPop R2025A; 2025; modelled',deprivation_source:preparednessData.source,deprivation_release:'2025; corrected 17 November 2025',deprivation_geography_note:p.imd_top10_pct==null?'Not matched to atlas geography':'Exact local-authority code match',census_reference_date:'2021-03-21',census_sources:censusData.sources.map(s=>s.source_url).join(' | '),census_geography_note:censusData.geography_note,census_calculation:'Published numerator / denominator * 100; crude disability rates',exported_at:new Date().toISOString()};});
 downloadTable(out,name);
}
$('analysisMetric').onchange=renderAnalysis;$('analysisSort').onchange=renderAnalysis;$('areaSearch').oninput=renderAnalysis;$('analysisExport').onclick=()=>exportRows(analysisRows,'England-local-authority-comparison.csv');$('mapTab').onclick=()=>{showMap();history.replaceState(null,'','#'+view);};$('analysisTab').onclick=showAnalysis;
function showSources(){openCatalogue();}for(const id of ['sourcesButton','sourcesTab'])$(id).onclick=showSources;$('closeSources').onclick=()=>$('sources').close();
function aliases(){const d=layer('districts'),h=layer('hexes');if(d){alias.district_boundaries={...d,id:'district_boundaries',title:'Local authority boundaries',style:{outline:true}};for(const[key,metric,title]of [['density','density_km2','Population density · local authorities'],['population','population_2025','Population · local authorities']])alias['district_'+key]={...d,id:'district_'+key,title,source:'WorldPop R2025A · ONS boundaries',date:'2025',style:{metric}};}if(h)for(const[key,metric,title]of [['density','density_km2','Population density · 5 km hexagons'],['population','population_2025','Population · 5 km hexagons']])alias['hex_'+key]={...h,id:'hex_'+key,title,style:{metric}};}
(async()=>{try{status('Opening England…');manifest=await getJSON('manifest.json');aliases();await initialisePreparedness();await initialiseFlood();initialiseWorkflows();initialiseCatalogue();Object.assign(METRICS,manifest.analysis_metrics||{});$('analysisMetric').replaceChildren();for(const [label,keys]of [['Community needs',Object.keys(NEEDS_METRICS)],['Flood exposure · high + medium',Object.keys(FLOOD_METRICS)],['Population and area',['population_2025','density_km2','area_km2']],['Environmental context',Object.keys(manifest.analysis_metrics).filter(k=>!NEEDS_METRICS[k]&&!FLOOD_METRICS[k])]]){const group=document.createElement('optgroup');group.label=label;for(const key of keys)group.append(new Option(METRICS[key].title,key));$('analysisMetric').append(group);}$('analysisMetric').value='imd_top10_pct';const outline=await getJSON('data/outline.geojson');L.geoJSON(outline,{pane:'countryOutline',interactive:false,style:{color:'#182d24',weight:1.15,fill:false}}).addTo(map);if(innerWidth<=1024)showPanel(false);fit();const hash=location.hash.slice(1),id={builtup:'settlement',transport:'towns'}[hash]||hash;setView(id==='analysis'?'clean':id||'clean');if(id==='analysis')showAnalysis();if(id==='partners-directory')showPartners();await restoreAtlasState();if(!pending.size)status('');}catch(e){status('Map could not open');toast(e.message);}})();
