'use strict';
// One category palette drives filters, map markers, cluster rings and spider legs.
const POINT_STYLES={
 towns:{city:['Cities','#7046a1'],town:['Towns','#ba641d'],village:['Villages','#218778']},
 education:{school:['Schools','#2868aa'],kindergarten:['Nurseries','#a74278'],college:['Colleges','#af681f'],university:['Universities','#7455ad']},
 healthcare:{hospital:['Hospitals','#b73748'],clinic:['Clinics','#237e89'],doctors:['Doctors','#416ab0'],pharmacy:['Pharmacies','#43814a'],dentist:['Dentists','#9661a3'],centre:['Health centres','#a76b20'],other:['Other healthcare','#65746d']},
 public_services:{police:['Police','#3766a0'],fire_station:['Fire stations','#c04937'],library:['Libraries','#8352a4'],community_centre:['Community centres','#24837a'],townhall:['Town halls','#a67420']},
 ports_airports:{aerodrome:['Airports / airfields','#376daa'],heliport:['Heliports','#8854a4'],harbour:['Ports / harbours','#b1782c'],port:['Ports / harbours','#b1782c'],other:['Other transport records','#806b53'],ferry_terminal:['Ferry terminals','#237f87']},
 stations:{station:['Rail stations','#336a9d'],halt:['Rail halts','#288b7e'],tram_stop:['Tram stops','#a24785']},
 power:{plant:['Power stations','#9b5133'],substation:['Substations','#9a7924'],generator:['Generators','#7360a5']},
 water_infrastructure:{water_works:['Water works','#237f90'],wastewater_plant:['Wastewater plants','#906246'],pumping_station:['Pumping stations','#7860a0'],water_tower:['Water towers','#356baf'],water_well:['Water wells','#438c70'],reservoir_covered:['Covered reservoirs','#a07926'],drinking_water:['Drinking water','#287699'],water_point:['Water points','#397b60']}
};
for(const [id,name]of Object.entries({towns:'Other place records',stations:'Other station records',power:'Other energy records',water_infrastructure:'Other water records',public_services:'Other public services',education:'Other education'}))POINT_STYLES[id].other=[name,'#69766e'];
const pointRenderers={};let spiderLayer=null;
function categoryStyle(l,cat){return POINT_STYLES[l.id]?.[cat]||[String(cat||'Other mapped features').replaceAll('_',' ').replace(/^./,c=>c.toUpperCase()),POINT_STYLES[l.id]?'#69766e':l.style?.color||'#69766e'];}
function pointCategories(l,features=[]){const raw=l.categories?Object.keys(l.categories):features.map(f=>f.properties.category);return [...new Set(raw.map(cat=>categoryFor(l,{properties:{category:cat}})))].filter(Boolean).sort((a,b)=>{const order=Object.keys(POINT_STYLES[l.id]||{});return (order.indexOf(a)<0?99:order.indexOf(a))-(order.indexOf(b)<0?99:order.indexOf(b))||a.localeCompare(b);});}
function pointRenderer(pane){return pointRenderers[pane]||(pointRenderers[pane]=L.svg({pane,padding:.3}));}
function pointName(l,f){return f.properties.name||categoryStyle(l,categoryFor(l,f))[0];}
function closeSpider(){if(spiderLayer){map.removeLayer(spiderLayer);spiderLayer=null;}}
function accessiblePoint(marker,label,action){marker.on('add',()=>{const el=marker.getElement();if(!el)return;if(el.ownerSVGElement){el.ownerSVGElement.setAttribute('role','group');el.ownerSVGElement.setAttribute('aria-label','Mapped locations');}el.setAttribute('tabindex','0');el.setAttribute('role','button');el.setAttribute('aria-label',label);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();action();}});});}
function featureMarker(l,f,position,pane){const cat=categoryFor(l,f),[title,clr]=categoryStyle(l,cat),radius=l.id==='towns'?({city:7,town:5.5,village:4}[cat]||4.5):5.5;
 const marker=L.circleMarker(position,{pane,renderer:pointRenderer(pane),radius,color:'#fff',weight:1.6,fillColor:clr,fillOpacity:1,bubblingMouseEvents:false});
 const open=()=>L.popup({maxWidth:320}).setLatLng(position).setContent(popup(l,f)).openOn(map);marker.on('click',open);marker.bindTooltip(esc(pointName(l,f))+' · '+esc(title),{direction:'top',className:'town-tip'});
 accessiblePoint(marker,pointName(l,f)+' — '+title,open);return marker;
}
function clusterContent(l,group){const box=document.createElement('div');box.className='cluster-browser';let page=0;
 function render(){box.replaceChildren();const title=document.createElement('h3');title.textContent=fmt(group.length)+' mapped locations';box.append(title);
 const hint=document.createElement('p');hint.className='area-note';hint.textContent='Choose a name to open its details.';box.append(hint);
 const list=document.createElement('div');list.className='cluster-list';for(const f of group.slice(page*30,(page+1)*30)){const b=document.createElement('button'),[name,colour]=categoryStyle(l,categoryFor(l,f));b.innerHTML='<i style="background:'+colour+'"></i><span>'+esc(pointName(l,f))+'<small>'+esc(name)+'</small></span>';b.onclick=()=>L.popup({maxWidth:320}).setLatLng([f.geometry.coordinates[1],f.geometry.coordinates[0]]).setContent(popup(l,f)).openOn(map);list.append(b);}box.append(list);
 if(group.length>30){const nav=document.createElement('div');nav.className='cluster-pages';for(const [label,delta,disabled]of [['Previous',-1,page===0],['Next',1,(page+1)*30>=group.length]]){const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.onclick=()=>{page+=delta;render();};nav.append(b);}const n=document.createElement('small');n.textContent=(page*30+1)+'–'+Math.min(group.length,(page+1)*30)+' of '+group.length;nav.append(n);box.append(nav);}}render();return box;}
function expandCluster(l,group,centre){closeSpider();const sorted=[...group].sort((a,b)=>pointName(l,a).localeCompare(pointName(l,b)));spiderLayer=L.featureGroup().addTo(map);
 if(group.length<=24){const origin=map.latLngToLayerPoint(centre);for(let i=0;i<sorted.length;i++){const f=sorted[i],angle=2*Math.PI*i/sorted.length-Math.PI/2,radius=sorted.length<=8?48:48+(i%2)*32,at=map.layerPointToLatLng(L.point(origin.x+Math.cos(angle)*radius,origin.y+Math.sin(angle)*radius));const clr=categoryStyle(l,categoryFor(l,f))[1];spiderLayer.addLayer(L.polyline([centre,at],{pane:'spiderPoints',renderer:pointRenderer('spiderPoints'),color:clr,weight:1.5,opacity:.7,interactive:false}));spiderLayer.addLayer(featureMarker(l,f,at,'spiderPoints'));}}
 L.popup({maxWidth:320,autoPan:false,className:'cluster-popup'}).setLatLng(centre).setContent(clusterContent(l,sorted)).openOn(map);
}
function drawPoints(entry,filtered){const l=entry.layer,z=map.getZoom(),buckets=new Map(),pane=l.id==='towns'?'townPoints':'placePoints';
 for(const f of filtered){const p=map.project([f.geometry.coordinates[1],f.geometry.coordinates[0]],z),cell=z>=14?22:54,key=Math.floor(p.x/cell)+'/'+Math.floor(p.y/cell);if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(f);}
 for(const group of buckets.values()){if(group.length===1){const f=group[0],c=f.geometry.coordinates;entry.mapLayer.addLayer(featureMarker(l,f,[c[1],c[0]],pane));continue;}
 let lat=0,lng=0;const counts=new Map();for(const f of group){lng+=f.geometry.coordinates[0];lat+=f.geometry.coordinates[1];const cat=categoryFor(l,f);counts.set(cat,(counts.get(cat)||0)+1);}let start=0;const segments=[],labels=[];for(const [cat,n]of counts){const [label,colour]=categoryStyle(l,cat),end=start+100*n/group.length;segments.push(colour+' '+start+'% '+end+'%');labels.push(label.toLowerCase()+': '+fmt(n));start=end;}
 const size=Math.min(48,30+Math.log(group.length)*2),count=group.length>=1000?fmt(group.length/1000,1)+'k':String(group.length),name=fmt(group.length)+' locations: '+labels.join(', ');
 const marker=L.marker([lat/group.length,lng/group.length],{pane,keyboard:false,bubblingMouseEvents:false,icon:L.divIcon({className:'osm-cluster',iconSize:[size,size],iconAnchor:[size/2,size/2],html:'<span class="cluster-ring" style="background:conic-gradient('+segments.join(',')+')"><span>'+count+'</span></span>'})});
 const open=()=>{if(z<10||(group.length>24&&z<17)){closeSpider();map.setView(marker.getLatLng(),Math.min(17,z+2));}else expandCluster(l,group,marker.getLatLng());};
 marker.bindTooltip(esc(name)+'<br>'+(z<10||(group.length>24&&z<17)?'Select to zoom in':'Select to expand and show names'),{className:'town-tip'});marker.on('click',open);accessiblePoint(marker,name,open);entry.mapLayer.addLayer(marker);}
}
function zoomNotice(l){const s=l.fast&&typeof DecompressionStream!=='undefined'?l.fast:l.spatial||l.overview;if(!s||map.getZoom()>=s.min_zoom)return null;const descriptions={roads:'Motorways shown; other major roads appear closer in.',towns:'Cities and towns shown; villages appear closer in.',power:'Power stations shown; generators and substations appear closer in.',railways:l.fast&&typeof DecompressionStream!=='undefined'?'Generalised railways shown; zoom in for individual tracks.':'Zoom in to see railway tracks.'};return {zoom:s.min_zoom,text:descriptions[l.id]||(!s.overview_count?'Zoom in to see these features.':null)};}
function renderZoomNotices(){let box=$('zoomNotices');if(!box){box=document.createElement('div');box.id='zoomNotices';box.setAttribute('aria-label','Layer visibility');$('themeControls').after(box);}box.replaceChildren();for(const id of new Set([primaryId,...contextIds])){const l=layer(id);if(!l)continue;const notice=zoomNotice(l);if(!notice?.text)continue;const row=document.createElement('div');row.className='zoom-notice';row.innerHTML='<span><strong>'+esc(l.title)+'</strong>'+esc(notice.text)+'</span>';const b=document.createElement('button');b.textContent='Zoom in';b.setAttribute('aria-label','Zoom in to show '+l.title+' detail');b.onclick=()=>map.setZoom(notice.zoom);row.append(b);box.append(row);}box.hidden=!box.children.length;}
